# Generated by Django 3.0.6 on 2020-06-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientsRegistered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('phone', models.CharField(default='', max_length=15)),
                ('email', models.CharField(default='', max_length=100)),
                ('message', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
