# Generated by Django 3.0.6 on 2020-05-22 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ahome_id', models.CharField(default='', max_length=10)),
                ('image_url', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ahome_id', models.CharField(default='', max_length=10)),
                ('property_type', models.CharField(default='', max_length=50)),
                ('action', models.CharField(default='', max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('city', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('zone', models.CharField(default='', max_length=100)),
                ('hood', models.CharField(default='', max_length=100)),
                ('addres', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('total_area', models.FloatField(default=0.0)),
                ('construction_area', models.FloatField(default=0.0)),
                ('rooms', models.CharField(default='', max_length=20)),
                ('half_baths', models.IntegerField(default=0)),
                ('baths', models.IntegerField(default=0)),
                ('parking', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
