# Generated by Django 3.0.6 on 2020-05-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0002_remove_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='rooms',
            field=models.IntegerField(default=0),
        ),
    ]
