# Generated by Django 3.0.6 on 2020-06-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0003_auto_20200524_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageproperty',
            name='image_url',
        ),
        migrations.AddField(
            model_name='imageproperty',
            name='number_of_images',
            field=models.IntegerField(default=0),
        ),
    ]
