# Generated by Django 3.0.6 on 2020-06-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0004_auto_20200606_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageproperty',
            name='format_image',
            field=models.CharField(default='png', max_length=10),
        ),
    ]
